services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./dev.env

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  # ui: