services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./dev.env
    networks:
      - rocketvote-network

  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./dev.env
    depends_on:
      - redis
    networks:
      - rocketvote-network
  
  celery_worker:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: celery -A rocketVoteAPI worker --beat --loglevel=info
    depends_on:
      - redis
      - api
    env_file:
      - ./dev.env
    networks:
      - rocketvote-network
  
  # nginx:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  #   networks:
  #     - rocketvote-network

networks:
  rocketvote-network:
    driver: bridge