services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./dev.env
    networks:
      - rocketvote-network

  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "${API_PORT}"
    env_file:
      - ./dev.env
    depends_on:
      - redis
    networks:
      - rocketvote-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80"
    depends_on:
      - api
    networks:
      - rocketvote-network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
    networks:
      - rocketvote-network

networks:
  rocketvote-network:
    driver: bridge