services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./dev.env
    networks:
      - rocketvote-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    volumes:
      - ./backend:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./dev.env
    depends_on:
      - redis
    networks:
      - rocketvote-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - rocketvote-network

networks:
  rocketvote-network:
    driver: bridge