FROM python:3.12

WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8080

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"]

CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8080", "rocketVoteAPI.wsgi:application"]