# Generated by Django 5.1.1 on 2024-12-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polltemplate',
            name='created_by',
            field=models.TextField(null=True),
        ),
    ]
